#!/usr/bin/env python
# coding: utf-8

# In[13]:


import pandas as pd
file_path = '/mnt/data/Sales.csv'
sales_data = pd.read_csv('Sales.csv')
#strip data
sales_data.columns = sales_data.columns.str.strip()
#Total revenue generated by each salesperson on each date:
pivot_total_revenue = sales_data.pivot_table(index='Date', columns='Salesperson', values='Revenue', aggfunc='sum')
#Average revenue per sale for each product:
avg_revenue_per_sale = sales_data.groupby('Product')['Revenue'].mean()
# Total units sold in each region on each date:
pivot_units_sold = sales_data.pivot_table(index='Date', columns='Region', values='Units Sold', aggfunc='sum')

max_units_per_salesperson = sales_data.groupby('Salesperson')['Units Sold'].max()

total_revenue = sales_data['Revenue'].sum()
revenue_by_region = sales_data.groupby('Region')['Revenue'].sum()
percentage_revenue_by_region = (revenue_by_region / total_revenue) * 100

sales_transactions = sales_data.groupby('Salesperson').size()

pivot_revenue_units = sales_data.pivot_table(index='Salesperson', columns='Product', values=['Revenue', 'Units Sold'], aggfunc='sum')

print("a) Total revenue generated by each salesperson on each date:\n", pivot_total_revenue)
print("\nb) Average revenue per sale for each product:\n", avg_revenue_per_sale)
print("\nc) Total units sold in each region on each date:\n", pivot_units_sold)
print("\nd) Maximum number of units sold in a single transaction by each salesperson:\n", max_units_per_salesperson)
print("\ne) Percentage of total revenue contributed by each region:\n", percentage_revenue_by_region)
print("\nf) Sales transactions count by each salesperson:\n", sales_transactions)
print("\ng) Total revenue and total units sold by each salesperson for each product:\n", pivot_revenue_units)

